name: Bygg KonCEPT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bygg-pdf:
    name: 'Bygg bok'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checka ut koden'
        uses: actions/checkout@v3
      - name: 'Installera Ubuntu-paket'
        run: |
          sudo apt-get --quiet update
          sudo apt-get --quiet --assume-yes --verbose-versions install texlive \
            texlive-lang-european texlive-science \
            texlive-fonts-recommended texlive-fonts-extra \
            language-pack-sv
      - name: 'Sätt systemspråk till svenska'
        run: |
          sudo locale-gen sv_SE.UTF-8
          sudo localectl set-locale LANG="sv_SE.UTF-8"
      - name: 'Kopiera info om repository'
        run: |
          echo $GITHUB_SHA | cut -c1-7 > SHA.tmp
          echo $GITHUB_REF_NAME > branch.tmp
      - name: 'Bygg koncept.pdf'
        run: make koncept.pdf
      - name: 'Lägg till versionsinformation i filnamnet'
        run: mv koncept.pdf koncept.$(cat VERSION.txt)+b${{ github.run_id }}.$(cat SHA.tmp).pdf
      - name: 'Beräkna checksumma'
        run: sha256sum koncept.$(cat VERSION.txt)+b${{ github.run_id }}.$(cat SHA.tmp).pdf >> $GITHUB_STEP_SUMMARY
      - name: 'Skapa rapporter'
        run: |
          sed -n '1p' koncept.log >> $GITHUB_STEP_SUMMARY
          make images_linked
          echo "Antal bilder med referenser: $(cat images_linked.txt | wc -l)" >> $GITHUB_STEP_SUMMARY
          make images_unlinked
          echo "Antal bilder utan referenser: $(cat images_unlinked.txt | wc -l)" >> $GITHUB_STEP_SUMMARY
          make TODOs
          echo "Antal TODO-kommentarer:&emsp;$(cat TODOs.txt | wc -l)" >> $GITHUB_STEP_SUMMARY
          make long_lines
          echo "Antal kodrader längre än 80 tecken: $(cat long_lines.txt | wc -l)" >> $GITHUB_STEP_SUMMARY
      - name: 'Spara PDF-artefakt'
        uses: actions/upload-artifact@v3
        with:
          name: koncept-pdf
          path: koncept*.pdf
      - name: 'Spara rapporter'
        uses: actions/upload-artifact@v3
        with:
          name: rapporter
          path: |
            images_linked.txt
            images_unlinked.txt
            TODOs.txt
            long_lines.txt
